### ISSUE TITLE
Error in running resnet50_trainer.py on MNIST data

### ISSUE THREAD

**Issue by weiyangedward** [facebookarchive/caffe2#1269]
Hi,

I installed Caffe2 and ran MNIST.ipynb without any problem. Now I am trying to run the distributed GPU sample code resnet50_trainer.py on the same MNIST dataset:

python resnet50_trainer.py --train_data ~/caffe2_notebooks/tutorial_data/mnist/mnist-train-nchw-lmdb/

 and see the following error:

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1500000
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0122640132904 secs
E0927 17:50:03.495896  7595 operator_schema.cc:83] Argument 'is_test' is required for Operator 'ImageInput'.
Traceback for operator 1886221678 in network resnet50
Traceback (most recent call last):
  File "resnet50_trainer.py", line 561, in <module>
    main()
  File "resnet50_trainer.py", line 557, in main
    Train(args)
  File "resnet50_trainer.py", line 402, in Train
    workspace.CreateNet(train_model.net)
  File "/usr/local/caffe2/python/workspace.py", line 152, in CreateNet
    StringifyProto(net), overwrite,
  File "/usr/local/caffe2/python/workspace.py", line 171, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at operator.cc:100] schema->Verify(operator_def). Operator def did not pass schema checking: input: "reader" output: "gpu_0/data" output: "gpu_0/label" name: "" type: "ImageInput" arg { name: "std" f: 128 } arg { name: "scale" i: 256 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "use_gpu_transform" i: 1 } arg { name: "cudnn_exhaustive_search" i: 1 } arg { name: "use_caffe_datum" i: 1 } arg { name: "use_cudnn" i: 1 } arg { name: "batch_size" i: 32 } arg { name: "mirror" i: 1 } arg { name: "output_type" s: "float" } arg { name: "crop" i: 227 } arg { name: "mean" f: 128 } device_option { device_type: 1 cuda_gpu_id: 0 } 

Any suggestions?

**Comment by pengbo-learn** [comment]
I had similar errors:

E0929 14:17:40.257784 10454 operator_schema.cc:99] Argument 'is_test' is required for Operator 'ImageInput'.

Traceback for operator 285837240 in network resnet50

Traceback (most recent call last):

  File "resnet50_trainer.py", line 564, in <module>

    main()

  File "resnet50_trainer.py", line 560, in main

    Train(args)

  File "resnet50_trainer.py", line 405, in Train

    workspace.CreateNet(train_model.net)

  File "/home/pengbo/caffe2/build/caffe2/python/workspace.py", line 167, in CreateNet

    StringifyProto(net), overwrite,

  File "/home/pengbo/caffe2/build/caffe2/python/workspace.py", line 186, in CallWithExceptionIntercept

    return func(*args, **kwargs)

RuntimeError: [enforce fail at operator.cc:116] schema->Verify(operator_def). Operator def did not pass schema checking: input: "reader" output: "gpu0/data" output: "gpu0/label" name: "" type: "ImageInput" arg { name: "std" f: 128 } arg { name: "scale" i: 256 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "use_gpu_transform" i: 1 } arg { name: "cudnn_exhaustive_search" i: 1 } arg { name: "use_caffe_datum" i: 1 } arg { name: "use_cudnn" i: 1 } arg { name: "batch_size" i: 32 } arg { name: "mirror" i: 1 } arg { name: "output_type" s: "float" } arg { name: "crop" i: 227 } arg { name: "mean" f: 128 } device_option { device_type: 1 cuda_gpu_id: 0 } 

solve by reverting the version to commit 6d2c27d8c46d1d2eb3f932145f4fcb9f9f9a6454.
maybe the new update introduces some errror, i guess

**Comment by simonschuang** [comment]
I have the same issue, fix by adding 'is_test' parameter.
```
--- a/caffe2/python/examples/resnet50_trainer.py
+++ b/caffe2/python/examples/resnet50_trainer.py
@@ -76,7 +76,8 @@ def AddImageInput(model, reader, batch_size, img_size, dtype):
         std=128.,
         scale=256,
         crop=img_size,
-        mirror=1
+        mirror=1,
+        is_test=False
```

**Comment by weiyangedward** [comment]
@simonschuang Wow! Brilliant! This solves my issue perfectly! Thanks a lot for this! How did you figure this out? I took a look at the caffe2 code base but it isn't clear to me why is_test=False works.

**Comment by weiyangedward** [comment]
@pengbo-learn Instead of reverting to another version and recompile, I added is_test=False and it works now. I didn't see this line of code in commit 6d2c27d though. Do you know what can be the cause of this error?

**Comment by pengbo-learn** [comment]
@weiyangedward I found this by chance, don't understand either.

**Comment by bddppq** [comment]
Sorry folks, the fix has just been landed 84047f0

It's fa0fcd4 that made all the "is_test" arguments required, since there are no tests covering these examples, I didn't notice this issue before.
