### ISSUE TITLE
Random big probability issue, in MPI training over TCP : "gloo/transport/tcp/pair.cc:536] : Connection refused"

### ISSUE THREAD

**Issue by shijieheping** [facebookarchive/caffe2#1335]
Hi All,
I have the following Error, when ran example training.
It happens in most runs, but the same command line works sometimes without throwing this error.
So I have to run the command again and again, until it start to train.

Any ideas?

_gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Intel(R) MPI Library for Linux* OS, Version 2017 Update 3 Build 20170405 (id: 17193)
Caffe2 commit: 91f63a2361fb8671e103a8d5601adec8354299b5_

```
[root@g1 examples]# **bs=64 if=br0 tr=tcp** traindata="/lustre/cfdata/imagenet_cars_boats_train" testdata="/lustre/cfdata/imagenet_cars_boats_val" filestore="/lustre/tmp"; mpirun -host g1 -n 1 python resnet50_trainer.py --train_data $traindata --test_data $testdata --num_gpus 2 --batch_size $bs **--num_shards=3 --shard_id=0 --run_id=1234** --file_store_path $filestore --distributed_transport=$tr --distributed_interface=$if : -host g2 -n 1 python resnet50_trainer.py --train_data $traindata --test_data $testdata  --num_gpus 2 --batch_size $bs **--num_shards=3 --shard_id=1 --run_id=1234** --file_store_path $filestore --distributed_transport=$tr --distributed_interface=$if : -host g4 -n 1 python resnet50_trainer.py --train_data $traindata --test_data $testdata  --num_gpus 2 --batch_size $bs **--num_shards=3 --shard_id=2 --run_id=1234** --file_store_path $filestore --distributed_transport=$tr --distributed_interface=$if

INFO:resnet50_trainer:Running on GPUs: [0, 1]
INFO:resnet50_trainer:Using epoch size: 1499904
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:resnet50_trainer:Running on GPUs: [0, 1]
INFO:resnet50_trainer:Using epoch size: 1499904
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:memonger:Memonger memory optimization took 0.0223760604858 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:data_parallel_model:Model for GPU : 1
INFO:memonger:Memonger memory optimization took 0.02073097229 secs
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:resnet50_trainer:Running on GPUs: [0, 1]
INFO:resnet50_trainer:Using epoch size: 1499904
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add initial parameter sync
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:memonger:Memonger memory optimization took 0.0224599838257 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0208330154419 secs
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0223860740662 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0211479663849 secs
E1013 17:02:39.707813 20540 common_world_ops.h:123] Caught gloo IO exception: **[/root/cf/caffe2/third_party/gloo/gloo/transport/tcp/pair.cc:536] connect [10.12.70.221]:13215: Connection refused**
E1013 17:02:39.709396 20540 net_simple.cc:76] Operator failed: input: "store_handler" output: "allreduce_0_cw" name: "allreduce_0_cw_op" type: "CreateCommonWorld" arg { name: "timeout_ms" i: 30000 } arg { name: "rank" i: 1 } arg { name: "interface" s: "br0" } arg { name: "status_blob" s: "create_allreduce_cw_0_status" } arg { name: "transport" s: "tcp" } arg { name: "size" i: 3 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
**E1013 17:02:39.709416 20540 workspace.cc:276] Error when running network resnet50_init**
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
Traceback for operator 535 in network resnet50_init
/root/cf/caffe2/build/caffe2/python/data_parallel_model.py:1684
/root/cf/caffe2/build/caffe2/python/data_parallel_model.py:1156
/root/cf/caffe2/build/caffe2/python/data_parallel_model.py:1207
/root/cf/caffe2/build/caffe2/python/data_parallel_model.py:1224
/root/cf/caffe2/build/caffe2/python/data_parallel_model.py:1072
/root/cf/caffe2/build/caffe2/python/data_parallel_model.py:271
resnet50_trainer.py:415
resnet50_trainer.py:575
resnet50_trainer.py:579
Traceback (most recent call last):
  File "resnet50_trainer.py", line 579, in <module>
    main()
  File "resnet50_trainer.py", line 575, in main
    Train(args)
  File "resnet50_trainer.py", line 418, in Train
    workspace.RunNetOnce(train_model.param_init_net)
  File "/root/cf/caffe2/build/caffe2/python/workspace.py", line 203, in RunNetOnce
    StringifyProto(net),
  File "/root/cf/caffe2/build/caffe2/python/workspace.py", line 186, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:924] gWorkspace->RunNetOnce(def).  
```

**Comment by thyeros** [comment]
try to increase the timeout value in gloo.

**Comment by shijieheping** [comment]
@minsikcho Thanks you miniskcho. Again it's also about MPI. Rebuilt with OpenMPI, and it was fixed.
Issue closed

**Comment by Applepleple** [comment]
Hi @shijieheping ,
I got just the same error like yours. Could you please tell me more about your fix about this problem?  Caffe2 is built with OpenMPI installed by "apt-get install" command.
libmpi_cxx.so.1 => /usr/lib/libmpi_cxx.so.1 (0x00007fe28b4bb000)
libmpi.so.12 => /usr/lib/libmpi.so.12 (0x00007fe28b1e5000)

Thanks a lot ^_^

**Comment by Applepleple** [comment]
Hi @shijieheping ,
I have solved this problem. I found that the "<ip-addr> <hostname>" pair in /etc/hosts should be changed from "127.0.1.1 hostname" to "<real-ip-addr> hostname", or Caffe2 would always try to connect 127.0.1.1:<port>, which caused the connection refused error.
