### ISSUE TITLE
resnet50_trainer.py example failed training

### ISSUE THREAD

**Issue by gjm441** [facebookarchive/caffe2#1368]
I need to convert my caffe2 model using fp16. I see the example resnet50_trainer.py. But I fails to train. I 
 use VOC0712 trainval lmdb data. This is my command and errors:
python examples/resnet50_trainer.py --train_data ~/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb/
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1500000
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0132730007172 secs
INFO:resnet50_trainer:Starting epoch 0/1000
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:333] error == cudaSuccess. 2 vs 0. Error at: /home/jmguo/caffe2/caffe2/core/context_gpu.cu:333: out of memory Error from operator: 
input: "gpu_0/comp_6_spatbn_2" input: "gpu_0/comp_6_conv_3_w" output: "gpu_0/comp_6_conv_3" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "enable_tensor_core" i: 0 } arg { name: "exhaustive_search" i: 1 } arg { name: "stride" i: 1 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "ws_nbytes_limit" i: 67108864 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1508739644 (unix time) try "date -d @1508739644" if you are using GNU date ***
PC: @     0x7ff147f1f428 gsignal
*** SIGABRT (@0x3e8000010f0) received by PID 4336 (TID 0x7ff0f37fe700) from PID 4336; stack trace: ***
    @     0x7ff1482c4390 (unknown)
    @     0x7ff147f1f428 gsignal
    @     0x7ff147f2102a abort
    @     0x7ff139b4084d __gnu_cxx::__verbose_terminate_handler()
    @     0x7ff139b3e6b6 (unknown)
    @     0x7ff139b3e701 std::terminate()
    @     0x7ff139b69d38 (unknown)
    @     0x7ff1482ba6ba start_thread
    @     0x7ff147ff082d clone
    @                0x0 (unknown)
Aborted (core dumped)
What's wrong? How can I fixed it? My caffe2 has alread build sucessfully and work well.

**Comment by gjm441** [comment]
I download mnist-lmdb and run resnet50_trainer.py face the same error.How can I fixed it? Thanks for help.
python examples/resnet50_trainer.py --train_data tutorials/mnist-lmdb/mnist-train-nchw-lmdb/ 
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
INFO:resnet50_trainer:Running on GPUs: [0]
INFO:resnet50_trainer:Using epoch size: 1500000
INFO:data_parallel_model:Parallelizing model for devices: [0]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
WARNING:data_parallel_model:------- DEPRECATED API, please use data_parallel_model.OptimizeGradientMemory() ----- 
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0117490291595 secs
INFO:resnet50_trainer:Starting epoch 0/1000
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:333] error == cudaSuccess. 2 vs 0. Error at: /home/jmguo/caffe2/caffe2/core/context_gpu.cu:333: out of memory Error from operator: 
input: "gpu_0/comp_12_sum_3" input: "gpu_0/comp_13_conv_1_w" output: "gpu_0/comp_13_conv_1" name: "" type: "Conv" arg { name: "kernel" i: 1 } arg { name: "enable_tensor_core" i: 0 } arg { name: "exhaustive_search" i: 1 } arg { name: "stride" i: 1 } arg { name: "pad" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "ws_nbytes_limit" i: 67108864 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1508743508 (unix time) try "date -d @1508743508" if you are using GNU date ***
PC: @     0x7fb7d16fa428 gsignal
*** SIGABRT (@0x3e8000007e0) received by PID 2016 (TID 0x7fb77cff9700) from PID 2016; stack trace: ***
    @     0x7fb7d1a9f390 (unknown)
    @     0x7fb7d16fa428 gsignal
    @     0x7fb7d16fc02a abort
    @     0x7fb7c331b84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fb7c33196b6 (unknown)
    @     0x7fb7c3319701 std::terminate()
    @     0x7fb7c3344d38 (unknown)
    @     0x7fb7d1a956ba start_thread
    @     0x7fb7d17cb82d clone
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by gjm441** [comment]
I have fix the problem.I use desktop 1050Ti which total RAM of 4GB.I put the batch size down to 8, and works well.
