### ISSUE TITLE
NCCL and dpm.Parallelize_GPU

### ISSUE THREAD

**Issue by matzeox** [facebookarchive/caffe2#1516]
Hello together,

today i have updated to the current master version of caffe2 (from an old caffe2 version, GIT-Commit: [77f037](https://github.com/caffe2/caffe2/commit/77f037df3195fc36ae53ee3ceb5f9da9b60fb747)).
If I set use_nccl = True in dpm.Parallelize_GPU() method, i get the following errors:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-3-e20b3ea577c7> in <module>()
      6     devices = gpus,
      7     optimize_gradient_memory = True,
----> 8     use_nccl = True
      9 
     10 )

/usr/local/caffe2/python/data_parallel_model.py in Parallelize_GPU(*args, **kwargs)
     42 def Parallelize_GPU(*args, **kwargs):
     43     kwargs['cpu_device'] = False
---> 44     Parallelize(*args, **kwargs)
     45 
     46 

/usr/local/caffe2/python/data_parallel_model.py in Parallelize(model_helper_obj, input_builder_fun, forward_pass_builder_fun, param_update_builder_fun, optimizer_builder_fun, post_sync_builder_fun, devices, rendezvous, net_type, broadcast_computed_params, optimize_gradient_memory, dynamic_memory_management, blobs_to_keep, use_nccl, max_concurrent_distributed_ops, cpu_device, num_threads_per_device, shared_model)
    256     log.info("Add gradient all-reduces for SyncSGD")
    257     if broadcast_computed_params:
--> 258         _BroadcastComputedParams(devices, model_helper_obj, rendezvous, use_nccl)
    259 
    260     if len(model_helper_obj._grad_names) > 0:

/usr/local/caffe2/python/data_parallel_model.py in _BroadcastComputedParams(devices, model, rendezvous, use_nccl)
   1403 def _BroadcastComputedParams(devices, model, rendezvous, use_nccl=False):
   1404     if rendezvous is None:
-> 1405         _BroadcastComputedParamsSingleHost(devices, model, use_nccl)
   1406     else:
   1407         _BroadcastComputedParamsDistributed(devices, model, rendezvous, use_nccl)

/usr/local/caffe2/python/data_parallel_model.py in _BroadcastComputedParamsSingleHost(devices, model, use_nccl)
   1428         # Copy from master to others -- averaging would be perhaps better,
   1429         # but currently NCCLAllReduce is too prone to deadlock
-> 1430         _Broadcast(devices, model, model.net, param_name, use_nccl)
   1431 
   1432 

/usr/local/caffe2/python/data_parallel_model.py in _Broadcast(devices, model, net, param, use_nccl)
    912                     viewvalues(model._device_grouped_blobs[param]),
    913                     viewvalues(model._device_grouped_blobs[param]),
--> 914                     root=0,
    915                 )
    916                 return

/usr/local/caffe2/python/core.py in <lambda>(*args, **kwargs)
   2039             )
   2040         return lambda *args, **kwargs: self._CreateAndAddToSelf(
-> 2041             op_type, *args, **kwargs)
   2042 
   2043     def __dir__(self):

/usr/local/caffe2/python/core.py in _CreateAndAddToSelf(self, op_type, inputs, outputs, **kwargs)
   2000         """A helper function to create an operator and add it to self.
   2001         """
-> 2002         inputs = _RectifyInputOutput(inputs)
   2003         for input in inputs:
   2004             if not self.BlobIsDefined(input):

/usr/local/caffe2/python/core.py in _RectifyInputOutput(blobs, net)
    301         raise TypeError(
    302             "Unknown input/output type: %s of type %s." %
--> 303             (str(blobs), type(blobs))
    304         )
    305 

TypeError: Unknown input/output type: dict_values([BlobReference("gpu_0/conv1_spatbn_relu_rm"), BlobReference("gpu_1/conv1_spatbn_relu_rm"), BlobReference("gpu_2/conv1_spatbn_relu_rm")]) of type <type 'dict_values'>.
```

If i leave NCCL = false everything works. Before i have updated to the newest version of caffe2, it also worked with NCCL. Thus, something must be happened with the usage of NCCL. I check it, once again (checked out git version 77f037) and it worked with NCCL = true!

Thanks

**Comment by slayton58** [comment]
\cc @akyrola 

Try casting lines 912, 913 in caffe2/python/data_parallel_model.py to `list` and see if that fixes your issue.

**Comment by matzeox** [comment]
Thank you for the hint.
I have casted the viewvalues into a python list and it works now with the current version! I have also created a pull request to fix this bug.
