### ISSUE TITLE
Run net_test fail

### ISSUE THREAD

**Issue by xwzy** [facebookarchive/caffe2#1796]
### System information

* Ubuntu 14.04
* g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
* cmake version 2.8.12.2
* Driver Version: 370.23, CUDA 8, CuDNN 5.1

### Output

```
$ ./net_test 
Running main() from gtest_main.cc
[==========] Running 12 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from NetDeathTest
[ RUN      ] NetDeathTest.DeclaredOutputNotMet
[       OK ] NetDeathTest.DeclaredOutputNotMet (0 ms)
[----------] 1 test from NetDeathTest (0 ms total)

[----------] 11 tests from NetTest
[ RUN      ] NetTest.ConstructionNoDeclaredInputOutput
[       OK ] NetTest.ConstructionNoDeclaredInputOutput (0 ms)
[ RUN      ] NetTest.ConstructionDeclaredInput
[       OK ] NetTest.ConstructionDeclaredInput (0 ms)
[ RUN      ] NetTest.ConstructionDeclaredOutput
[       OK ] NetTest.ConstructionDeclaredOutput (0 ms)
[ RUN      ] NetTest.DeclaredInputInsufficient
[       OK ] NetTest.DeclaredInputInsufficient (1 ms)
[ RUN      ] NetTest.ChainingForLinearModel
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0124 17:12:38.767187  4086 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 3.365e-06 secs
I0124 17:12:38.767282  4086 net_dag.cc:61] Number of parallel execution chains 1 Number of operators = 2
[       OK ] NetTest.ChainingForLinearModel (1 ms)
[ RUN      ] NetTest.ChainingForDifferentDevices
unknown file: Failure
C++ exception with description "[enforce fail at common_gpu.cc:144] error == cudaSuccess. 10 vs 0. Error at: /home/wzy/caffe2/caffe2/core/common_gpu.cc:144: invalid device ordinal " thrown in the test body.
[  FAILED  ] NetTest.ChainingForDifferentDevices (719 ms)
[ RUN      ] NetTest.ChainingForFork
I0124 17:12:39.487208  4086 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 2.401e-06 secs
I0124 17:12:39.487243  4086 net_dag.cc:61] Number of parallel execution chains 3 Number of operators = 3
[       OK ] NetTest.ChainingForFork (1 ms)
[ RUN      ] NetTest.ChainingForForkJoin
I0124 17:12:39.488157  4086 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 2.533e-06 secs
I0124 17:12:39.488171  4086 net_dag.cc:61] Number of parallel execution chains 3 Number of operators = 4
[       OK ] NetTest.ChainingForForkJoin (1 ms)
[ RUN      ] NetTest.ChainingForwardBackward
I0124 17:12:39.489321  4086 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 9.876e-06 secs
I0124 17:12:39.489347  4086 net_dag.cc:61] Number of parallel execution chains 1 Number of operators = 25
[       OK ] NetTest.ChainingForwardBackward (1 ms)
[ RUN      ] NetTest.ChainingForHogwildModel
I0124 17:12:39.490159  4086 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 2.382e-06 secs
I0124 17:12:39.490172  4086 net_dag.cc:61] Number of parallel execution chains 2 Number of operators = 6
[       OK ] NetTest.ChainingForHogwildModel (0 ms)
[ RUN      ] NetTest.FailingOperator
I0124 17:12:39.490770  4086 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.172e-06 secs
I0124 17:12:39.490782  4086 net_dag.cc:61] Number of parallel execution chains 1 Number of operators = 2
E0124 17:12:39.490833  4116 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.490855  4086 net.h:70] Failed to execute async run
E0124 17:12:39.490881  4121 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.490902  4086 net.h:70] Failed to execute async run
E0124 17:12:39.490927  4125 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.490947  4086 net.h:70] Failed to execute async run
E0124 17:12:39.490969  4129 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.490984  4086 net.h:70] Failed to execute async run
E0124 17:12:39.491005  4133 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.491020  4086 net.h:70] Failed to execute async run
E0124 17:12:39.491044  4137 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.491060  4086 net.h:70] Failed to execute async run
E0124 17:12:39.491080  4141 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.491096  4086 net.h:70] Failed to execute async run
E0124 17:12:39.491125  4145 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.491142  4086 net.h:70] Failed to execute async run
E0124 17:12:39.491163  4149 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.491178  4086 net.h:70] Failed to execute async run
E0124 17:12:39.491201  4153 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0124 17:12:39.491217  4086 net.h:70] Failed to execute async run
[       OK ] NetTest.FailingOperator (1 ms)
[----------] 11 tests from NetTest (725 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 2 test cases ran. (725 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NetTest.ChainingForDifferentDevices

 1 FAILED TEST
```

**Comment by orionr** [comment]
@xwzy thanks for sending this. I just confirmed I can run this on the latest version of master with Ubuntu 14.04 via docker. Typically we run with

```
cd caffe2
mkdir build && cd build
cmake ..
sudo make install
make test
```

but I confirmed running `./net_test` inside the `build/bin` directory also worked for me.

Do you have the latest version of source? There was a fix about a month back (https://github.com/caffe2/caffe2/commit/6d7a2302eb983fee3dc8ea8bce76b26e84f9d519) that might have caused this. Also referenced in https://github.com/caffe2/caffe2/issues/1533

**Comment by ristar17** [comment]
I have the same problem.I used cudnn7_7.0.5.15-1 ,  cuda8.0, ubuntu 14.04. How to solve this problem?

**Comment by pietern** [comment]
@xwzy How many GPU cards do you have in your machine?

**Comment by pietern** [comment]
The warnings are intentional: cuDNN 5.1 support is best effort and we recommend upgrading to 7.0.

**Comment by xwzy** [comment]
@pietern Only one GTX 1070

**Comment by xwzy** [comment]
It looks like @ristar17 has the same problem with CuDNN 7

**Comment by cvpr** [comment]
I have the same problem. I use cudnn6, only one GTX1080

**Comment by cvpr** [comment]
NetTest.ChainingForLinearModel (3 ms)
[ RUN      ] NetTest.ChainingForDifferentDevices
unknown file: Failure
C++ exception with description "[enforce fail at common_gpu.cc:144] error == cudaSuccess. 10 vs 0. Error at: /home/zhangyk/work/caffe2/caffe2/caffe2/core/common_gpu.cc:144: invalid device ordinal " thrown in the test body.
[  FAILED  ] NetTest.ChainingForDifferentDevices (170 ms)

**Comment by cvpr** [comment]
zhangyk@zhangyk:~/work/caffe2/caffe2/build/bin$ ./net_test
Running main() from gtest_main.cc
[==========] Running 12 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from NetDeathTest
[ RUN      ] NetDeathTest.DeclaredOutputNotMet
[       OK ] NetDeathTest.DeclaredOutputNotMet (0 ms)
[----------] 1 test from NetDeathTest (0 ms total)

[----------] 11 tests from NetTest
[ RUN      ] NetTest.ConstructionNoDeclaredInputOutput
[       OK ] NetTest.ConstructionNoDeclaredInputOutput (0 ms)
[ RUN      ] NetTest.ConstructionDeclaredInput
[       OK ] NetTest.ConstructionDeclaredInput (0 ms)
[ RUN      ] NetTest.ConstructionDeclaredOutput
[       OK ] NetTest.ConstructionDeclaredOutput (0 ms)
[ RUN      ] NetTest.DeclaredInputInsufficient
[       OK ] NetTest.DeclaredInputInsufficient (0 ms)
[ RUN      ] NetTest.ChainingForLinearModel
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0126 11:49:49.485837  3892 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 4.846e-06 secs
I0126 11:49:49.485961  3892 net_dag.cc:61] Number of parallel execution chains 1 Number of operators = 2
[       OK ] NetTest.ChainingForLinearModel (3 ms)
[ RUN      ] NetTest.ChainingForDifferentDevices
unknown file: Failure
C++ exception with description "[enforce fail at common_gpu.cc:144] error == cudaSuccess. 10 vs 0. Error at: /home/zhangyk/work/caffe2/caffe2/caffe2/core/common_gpu.cc:144: invalid device ordinal " thrown in the test body.
[  FAILED  ] NetTest.ChainingForDifferentDevices (170 ms)
[ RUN      ] NetTest.ChainingForFork
I0126 11:49:49.658179  3892 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 3.279e-06 secs
I0126 11:49:49.658231  3892 net_dag.cc:61] Number of parallel execution chains 3 Number of operators = 3
[       OK ] NetTest.ChainingForFork (1 ms)
[ RUN      ] NetTest.ChainingForForkJoin
I0126 11:49:49.659658  3892 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 2.974e-06 secs
I0126 11:49:49.659682  3892 net_dag.cc:61] Number of parallel execution chains 3 Number of operators = 4
[       OK ] NetTest.ChainingForForkJoin (1 ms)
[ RUN      ] NetTest.ChainingForwardBackward
I0126 11:49:49.660887  3892 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.5187e-05 secs
I0126 11:49:49.660930  3892 net_dag.cc:61] Number of parallel execution chains 1 Number of operators = 25
[       OK ] NetTest.ChainingForwardBackward (1 ms)
[ RUN      ] NetTest.ChainingForHogwildModel
I0126 11:49:49.661940  3892 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 3.657e-06 secs
I0126 11:49:49.661965  3892 net_dag.cc:61] Number of parallel execution chains 2 Number of operators = 6
[       OK ] NetTest.ChainingForHogwildModel (1 ms)
[ RUN      ] NetTest.FailingOperator
I0126 11:49:49.662708  3892 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.511e-06 secs
I0126 11:49:49.662726  3892 net_dag.cc:61] Number of parallel execution chains 1 Number of operators = 2
E0126 11:49:49.662813  3917 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.662847  3892 net.h:70] Failed to execute async run
E0126 11:49:49.662900  3921 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.662951  3892 net.h:70] Failed to execute async run
E0126 11:49:49.662988  3925 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663019  3892 net.h:70] Failed to execute async run
E0126 11:49:49.663059  3932 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663089  3892 net.h:70] Failed to execute async run
E0126 11:49:49.663130  3936 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663156  3892 net.h:70] Failed to execute async run
E0126 11:49:49.663192  3940 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663223  3892 net.h:70] Failed to execute async run
E0126 11:49:49.663260  3944 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663286  3892 net.h:70] Failed to execute async run
E0126 11:49:49.663342  3948 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663365  3892 net.h:70] Failed to execute async run
E0126 11:49:49.663420  3949 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663444  3892 net.h:70] Failed to execute async run
E0126 11:49:49.663486  3956 net_dag.cc:212] Operator chain failed: input: "in" output: "hidden" type: "NetTestDummy"
E0126 11:49:49.663511  3892 net.h:70] Failed to execute async run
[       OK ] NetTest.FailingOperator (1 ms)
[----------] 11 tests from NetTest (178 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 2 test cases ran. (179 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NetTest.ChainingForDifferentDevices

 1 FAILED TEST

**Comment by ristar17** [comment]
I change to 'cuDNN v6.0 (April 27, 2017), for CUDA 8.0' ,however, the problem is as before. The device is GTX1080.

**Comment by cvpr** [comment]
@pietern  could you help solve this problem? I use ubuntu 16.04, cuda8.0, cudnn6, one GTX1080 card. I don't use docker .  Compiling seems no problem.

**Comment by Yangqing** [comment]
Looks like #1826 should fix this - I am closing it for now but please feel free to reopen if the problem persists.
