### ISSUE TITLE
libnccl.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by danfouer** [facebookarchive/caffe2#1825]
Test the Caffe2 Installation
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Segmentation fault (core dumped)
Failure
Segmentation fault (core dumped)

danfouer@GPU1070:~$ cd caffe2/build
danfouer@GPU1070:~/caffe2/build$ python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Success

danfouer@GPU1070:~/caffe2/build$ echo $PYTHONPATH/usr/local::/home/caffe2/build
danfouer@GPU1070:~/caffe2/build$ echo $LD_LIBRARY_PATH/usr/local/lib:

**Comment by pjh5** [comment]
Can you start a python interpreter and run `from caffe2.python import core` inside it? This will give us a better error message.

Can you also post the operating system you are using and whether you're using Anaconda?

**Comment by pjh5** [comment]
@danfouer are you still having this issue?

**Comment by SAGGSOC** [comment]
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)

**Comment by pjh5** [comment]
@SAGGSOC have you installed NCCL? https://developer.nvidia.com/nccl

**Comment by SAGGSOC** [comment]
Problem is solved. Thank you.

**Comment by pjh5** [comment]
@VajiraPrabuddhaka if you're not getting the exact error message above then it's a different problem and you should open a new issue at https://github.com/pytorch/pytorch/issues

If you are getting the same error message, then how did you install NCCL?

**Comment by luchy01** [comment]
i got the same exact error as stated above.

python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'

when i try to run with command as show above i got this error. 

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory

i installed the nccl2 with command:
conda install -c pytorch nccl2

i m using anaconda environment. 

Please help, thanks.
