### ISSUE TITLE
/usr/local/nvidia/lib/libcuda.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by encorechow** [facebookarchive/caffe2#1887]
I am trying to build caffe2 in a ubuntu16.04 docker container.
The image is based on nvidia official cuda8.0-cudnn6-devel-ubuntu16.04. The error as follows:

```[  0%] Built target pthreadpool
[  3%] Built target cpuinfo
[  6%] Built target nnpack
[  8%] Built target nnpack_reference_layers
[  8%] Built target gtest
[  8%] Built target gtest_main
[ 10%] Built target benchmark
[ 13%] Built target gloo
[ 15%] Built target gloo_cuda
[ 15%] Built target gloo_builder
[ 15%] Built target Caffe_PROTO
[ 15%] Built target python_copy_files
[ 16%] Built target Caffe2_PROTO
[ 17%] Built target Caffe2_perfkernels_avx2
[ 17%] Built target Caffe2_perfkernels_avx
[ 17%] Linking CXX shared library ../lib/libcaffe2.so
/usr/local/nvidia/lib/libcuda.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2.dir/build.make:7134: recipe for target 'lib/libcaffe2.so' failed
make[2]: *** [lib/libcaffe2.so] Error 1
CMakeFiles/Makefile2:3186: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
I guess it should find /usr/local/nvidia/lib64/libcuda.so, but get /usr/local/nvidia/lib/libcuda.so instead. Can anyone help with this?

**Comment by pjh5** [comment]
We have a CI build on that exact environment but don't see any problems on our end. Can you try looking at our build steps for it at https://github.com/caffe2/caffe2/blob/master/docker/jenkins/ubuntu-cuda/Dockerfile , which uses the scripts in https://github.com/caffe2/caffe2/tree/master/docker/jenkins/common and see if you can copy or adapt them for your use case?

**Comment by encorechow** [comment]
@pjh5 Thanks for your reply
I solved it by manually add NO_SYSTEM_ENVIRONMENT_PATH to the cmake find_library function in Cuda.cmake. But I guess my system environment put the lib directory before lib64.

**Comment by woodenchild** [comment]
@encorechow  Hi, can you teach me how to solve this problem? I am a novice. I don't find the Cuda.cmake file and how to add the path. Thank you very much.

**Comment by Jilliansea** [comment]
have you solved the problem, please? @woodenchild

**Comment by tlatlbtle** [comment]
same issue @woodenchild

**Comment by wjbKimberly** [comment]
Hi all,
I think woodenchild he means that we can run cmake with additional paramter like:
cmake .. -DNO_SYSTEM_ENVIRONMENT_PATH=/usr/local/nvidia/lib/

I tried it and successfully build caffe2.

**Comment by echoukse** [comment]
The solution is this: 
In your cmake/public/cuda.cmake:
find_library(CUDA_CUDA_LIB cuda
    PATHS ${CUDA_TOOLKIT_ROOT_DIR}
    PATH_SUFFIXES lib64 lib lib/stubs lib64/stubs lib/x64 **NO_SYSTEM_ENVIRONMENT_PATH**)
