### ISSUE TITLE
import caffe2 in jupyter just stuck

### ISSUE THREAD

**Issue by RunziiMo** [facebookarchive/caffe2#2003]
I'm using jupyter on my mac, I found that it would stuck there and there would be no response if I
ever execute
```
from caffe2.python import core, workspace
```
and jupyter would simply show `ln [ * ]` for ever
I can successfully execute this through my python command line.
Besides, I'm not using GPU support, and this problem happens in jupyter notebook. When I switch to jupyter console, it shows 
```
/Users/xxx/Desktop/caffe2/caffe2/python/core.py in <module>()
     27 from six import binary_type, string_types, text_type
     28 
---> 29 from caffe2.proto import caffe2_pb2
     30 from caffe2.python import scope, utils, workspace
     31 from caffe2.python.control_ops_grad import \

ImportError: cannot import name caffe2_pb2
```

**Comment by orionr** [comment]
@RunziiMo did you use the script
```
scripts/start_ipython_notebook.sh
```
to start Jupyter? Also make sure you activated your conda environment (if you used that) before running the script.

**Comment by SteveCruz** [comment]
You could try to add the path to your caffe2 installation manually in your ipynb script like:

```
import sys
sys.path.append('/usr/local/caffe2/build')

import caffe2
```

I had the same issue in jupyter notebook (without conda), where caffe2 could be imported in the command line or other IDEs, but not within jupyter notebook, because some path variables were not set or loaded correctly.

**Comment by RunziiMo** [comment]
@orionr I used that but it didn't work. And yeah I can successfully excute `python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"` and it shows `Success`. Luckily, I solved import error problem now. But import caffe2.python.core still stuck.

**Comment by nykabhishek** [comment]
@RunziiMo Could you please explain how you solve the import problem?

**Comment by RunziiMo** [comment]
@nykabhishek I found I forget to add `export PYTHONPATH=/usr/local:$PYTHONPATH` to ~/.bash_profile. And I found that the install tutorial changed on [caffe2.ai](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt), I can now install caffe2 by Pre-Built Binaries on Mac. So I execute `sudo rm -rf /usr/local/caffe*` and reinstall by `conda install -c caffe2 caffe2`. And import problem solved.

**Comment by nykabhishek** [comment]
Yeah even I figured it out. I had a typo in my `PYTHONPATH`. Thanks for the update. Maybe we can go ahead and close this issue.

**Comment by youngxiao** [comment]
@nykabhishek I build caffe2 from source. And I can successfully execute `python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure" ` and it shows Success. But when I execute `python caffe2/python/operator_test/relu_op_test.py` to test whether GPU support. It shows a `caffe2_pb2` Import Error. So may I ask you how do you solve your `caffe2_pb2` Import Error?
