### ISSUE TITLE
cmake 3.10.2 build error, 3.5.1 no problem

### ISSUE THREAD

**Issue by vsooda** [facebookarchive/caffe2#2019]
If this is a build issue, please fill out the template below.

### System information

* Operating system:ubuntu16.04
* Compiler version:gcc4.9/gcc5.4
* CMake version: 3.10.2
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):

### CMake summary output

```
[ 76%] Linking CXX shared library ../lib/libcaffe2_gpu.so
c++: error: /usr/local/cuda-8.0/lib64/libcublas.so;/usr/local/cuda-8.0/lib64/libcublas_device.a: No such file or directory
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:44843: recipe for target 'lib/libcaffe2_gpu.so' failed
make[2]: *** [lib/libcaffe2_gpu.so] Error 1
CMakeFiles/Makefile2:1919: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I checked the link.txt, it  must be wrong(where I had make it bold).

caffe2/CMakeFiles/conv_op_test.dir/link.txt
1:/usr/bin/c++   -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization -O3 -DNDEBUG  -Wl,-rpath -Wl,/usr/lib/openmpi/lib -Wl,--enable-new-dtags -pthread -rdynamic CMakeFiles/conv_op_test.dir/share/contrib/nnpack/conv_op_test.cc.o  -o ../bin/conv_op_test -Wl,-rpath,/home/sooda/deep/caffe2/build/lib:/usr/lib/openmpi/lib:/usr/local/cuda-8.0/lib64:/usr/local/lib: -Wl,--no-as-needed -Wl,--as-needed -Wl,--no-as-needed ../lib/libcaffe2_gpu.so -Wl,--as-needed /usr/lib/x86_64-linux-gnu/libprotobuf.so -pthread ../lib/libnnpack.a ../lib/libcpuinfo.a /usr/lib/x86_64-linux-gnu/libgflags.so /usr/lib/x86_64-linux-gnu/libglog.so -llmdb -lleveldb -lsnappy /usr/lib/openmpi/lib/libmpi_cxx.so /usr/lib/openmpi/lib/libmpi.so ../lib/libgloo.a -lgcc_s -lgcc -ldl /usr/lib/x86_64-linux-gnu/libcuda.so /usr/local/cuda-8.0/lib64/libcudart_static.a /usr/local/cuda-8.0/lib64/libcurand.so **"/usr/local/cuda-8.0/lib64/libcublas.so;/usr/local/cuda-8.0/lib64/libcublas_device.a"** /usr/local/cuda-8.0/lib64/libcudnn.so /usr/local/cuda-8.0/lib64/libnvrtc.so ../lib/libgloo_cuda.a ../lib/libgtest_main.a ../lib/libcaffe2.so /usr/lib/x86_64-linux-gnu/libprotobuf.so /usr/lib/x86_64-linux-gnu/libgflags.so /usr/lib/x86_64-linux-gnu/libglog.so /usr/local/lib/libopencv_highgui.so.2.4.9 /usr/local/lib/libopencv_imgproc.so.2.4.9 /usr/local/lib/libopencv_core.so.2.4.9 ../lib/libgloo.a /usr/lib/openmpi/lib/libmpi_cxx.so /usr/lib/openmpi/lib/libmpi.so /usr/local/cuda-8.0/lib64/libcudart.so -lcuda /usr/local/cuda-8.0/lib64/libnvrtc.so -lpthread /usr/local/cuda-8.0/lib64/libcudart_static.a -ldl -lrt ../lib/libgtest.a -pthread

**Comment by pjh5** [comment]
This is a known issue fixed by https://github.com/caffe2/caffe2/pull/2004 . It should be merged shortly, but you can copy the changes in cmake/public/Cuda.cmake to your local copy to fix it sooner.
