### ISSUE TITLE
ls: cannot access '/usr/lib//libcudart.so.*': No such file or directory  on Debian GNU/Linux 9.3

### ISSUE THREAD

**Issue by anatlin** [facebookarchive/caffe2#2198]
When running ```make install``` , I get 
```
Scanning dependencies of target nccl_external
[  0%] Creating directories for 'nccl_external'
[  1%] No download step for 'nccl_external'
[  1%] No patch step for 'nccl_external'
[  1%] No update step for 'nccl_external'
[  1%] No configure step for 'nccl_external'
[  1%] Performing build step for 'nccl_external'
ls: cannot access '/usr/lib//libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib//libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib//libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib//libcudart.so.*': No such file or directory
```
This happens even though the CMAKE has found libcudart.so in ```CUDA runtime library: /usr/lib/x86_64-linux-gnu/libcudart.so``` (see summary )

### System information

* Operating system: Debian GNU/Linux 9.3 (stretch)
* Compiler version: gcc version 6.3.0 20170516 (Debian 6.3.0-18) 
* CMake version: cmake version 3.9.5
* CMake arguments: -DCMAKE_PREFIX_PATH=~/anaconda2/envs/my_caffe2_env -DCMAKE_INSTALL_PREFIX=/~/anaconda2/envs/my_caffe2_env -DCUDNN_INCLUDE_DIR=~/src2/cudnn-9.0-linux-x64-v7/include/ -DCUDNN_LIBRARY=~/src2/cudnn-9.0-linux-x64-v7/lib64/
* Relevant libraries/versions (e.g. CUDA): CUDA 9.0

### CMake summary output

```
-- ******** Summary ********
-- General:
--   CMake version         : 3.9.5
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1288-gec3934007
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 6.3.0
--   Protobuf compiler     : ~/anaconda2/envs/my_caffe2_env/bin/protoc
--   Protobuf include path : ~/anaconda2/envs/my_caffe2_env/include
--   Protobuf libraries    : ~/anaconda2/envs/my_caffe2_env/lib/libprotobuf.so;-lpthread
--   BLAS                  : Eigen
--   CXX flags             :  -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.14
--     Python includes     : ~/anaconda2/envs/my_caffe2_env/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 9.0
--     CuDNN version       : 7.0.5
--     CUDA root directory : /usr
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/lib/x86_64-linux-gnu/libnvrtc.so
--     CUDA runtime library: /usr/lib/x86_64-linux-gnu/libcudart.so
--     CUDA include path   : /usr/include
--     NVCC executable     : /usr/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : ..
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.21
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.3.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done

```

**Comment by pjh5** [comment]
Can you pass VERBOSE=1 to your make command give me the linking and compiler commands right before this error occurs? Something must be referring to /usr/lib/libcudart.so , it may either be a bug somewhere in our code or in an installation problem on your machine. If you run `ldd` on /usr/lib/x86_64-linux-gnu/libcuda.so and libnvrtc.so and also tell me which NCCL you're using ( is it being built from third_party (should say in the cmake output) or did you install your own from Nvidia's website?)?

**Comment by anatlin** [comment]
```make VERBOSE=1 install```

gives me
```
/usr/bin/cmake -H~/caffe2 -B~/caffe2/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start ~/caffe2/build/CMakeFiles ~/caffe2/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '~/caffe2/build'
make -f CMakeFiles/nccl_external.dir/build.make CMakeFiles/nccl_external.dir/depend
make[2]: Entering directory '~/caffe2/build'
cd ~/caffe2/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" ~/caffe2 ~/caffe2 ~/caffe2/build ~/caffe2/build ~/caffe2/build/CMakeFiles/nccl_external.dir/DependInfo.cmake --color=
make[2]: Leaving directory '~/caffe2/build'
make -f CMakeFiles/nccl_external.dir/build.make CMakeFiles/nccl_external.dir/build
make[2]: Entering directory '~/caffe2/build'
[  0%] Performing build step for 'nccl_external'
cd ~/caffe2/third_party/nccl && make CXX=/usr/bin/c++ CUDA_HOME=/usr NVCC=/usr/bin/nvcc
make[3]: Entering directory '~/caffe2/third_party/nccl'
ls: cannot access '/usr/lib//libcudart.so.*': No such file or directory

```

and 
```
>$ ldd /usr/lib/x86_64-linux-gnu/libcuda.so
        linux-vdso.so.1 (0x00007fff0c755000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f518dc7a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f518d8db000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f518d6d7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f518d4ba000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f518d2b2000)
        libnvidia-fatbinaryloader.so.390.25 => /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.390.25 (0x00007f518d066000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f518eb1e000)

>$ ldd /usr/lib/x86_64-linux-gnu/libnvrtc.so
        linux-vdso.so.1 (0x00007ffcdeeeb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9ce6f03000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9ce6cff000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9ce6af7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9ce67f3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9ce6454000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9ce896b000)
```

and nccl seems to be coming from the third party
```
-- Found nccl: ~/caffe2/third_party/nccl/build/include  
```

**Comment by pjh5** [comment]
I think the problem is that this cmake command https://github.com/caffe2/caffe2/blob/master/cmake/External/nccl.cmake#L23 is not looking under lib/x86_64-linux-gnu . Can you add
`set(CMAKE_FIND_LIBRARY_PREFIXES "${CMAKE_FIND_LIBRARY_PREFIXES};lib/x86_64-linux-gnu") right before that line and try again?

Installing NCCL yourself from Nvidia might also fix it too, as then Caffe2 won't build NCCL from third_party.

**Comment by toby5box** [comment]
I'm having the same problem on Ubuntu 17.10:

```
# make
[  0%] Performing build step for 'nccl_external'
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
Compiling src/libwrap.cu                      > /root/caffe2/third_party/nccl/build/obj/libwrap.o
In file included from /usr/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
Makefile:111: recipe for target '/root/caffe2/third_party/nccl/build/obj/libwrap.o' failed
make[3]: *** [/root/caffe2/third_party/nccl/build/obj/libwrap.o] Error 1
CMakeFiles/nccl_external.dir/build.make:110: recipe for target 'nccl_external-prefix/src/nccl_external-stamp/nccl_external-build' failed
make[2]: *** [nccl_external-prefix/src/nccl_external-stamp/nccl_external-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nccl_external.dir/all' failed
make[1]: *** [CMakeFiles/nccl_external.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
root@w8pc:~/caffe2/build# dpkg -l|grep cuda
ii  caffe-cuda                                 1.0.0-3build1                               amd64        Fast, open framework for Deep Learning (Meta)
ii  caffe-tools-cuda                           1.0.0-3build1                               amd64        Tools for fast, open framework for Deep Learning (CUDA)
ii  libcaffe-cuda1:amd64                       1.0.0-3build1                               amd64        library of Caffe, deep leanring framework (CUDA)
ii  libcuda1-384                               384.111-0ubuntu0.17.10.1                    amd64        NVIDIA CUDA runtime library
ii  libcudart8.0:amd64                         8.0.61-1                                    amd64        NVIDIA CUDA Runtime Library
ii  nvidia-cuda-dev                            8.0.61-1                                    amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc                            8.0.61-1                                    all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                            8.0.61-1                                    amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                        8.0.61-1                                    amd64        NVIDIA CUDA development toolkit
ii  python3-caffe-cuda                         1.0.0-3build1                               amd64        Python3 interface of Caffe (CUDA)
root@w8pc:~/caffe2/build# find /usr -name libcudart.so.*
/usr/lib/x86_64-linux-gnu/libcudart.so.8.0
/usr/lib/x86_64-linux-gnu/libcudart.so.8.0.61
```

**Comment by toby5box** [comment]
Same problem on my Ubuntu 17.10 (CUDA 8.0) system:

```
root@w8pc:~/caffe2/build# make
[  1%] Creating directories for 'nccl_external'
[  1%] No download step for 'nccl_external'
[  1%] No patch step for 'nccl_external'
[  1%] No update step for 'nccl_external'
[  1%] No configure step for 'nccl_external'
[  1%] Performing build step for 'nccl_external'
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
Compiling src/libwrap.cu                      > /root/caffe2/third_party/nccl/build/obj/libwrap.o
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
ls: cannot access '/usr/lib64/libcudart.so.*': No such file or directory
Compiling src/core.cu                         > /root/caffe2/third_party/nccl/build/obj/core.o
src/core.cu(719): error: expected an expression

src/core.cu(719): error: expected an expression

2 errors detected in the compilation of "/tmp/tmpxft_00000dc9_00000000-15_core.compute_61.cpp1.ii".
Makefile:111: recipe for target '/root/caffe2/third_party/nccl/build/obj/core.o' failed
make[3]: *** [/root/caffe2/third_party/nccl/build/obj/core.o] Error 2
CMakeFiles/nccl_external.dir/build.make:110: recipe for target 'nccl_external-prefix/src/nccl_external-stamp/nccl_external-build' failed
make[2]: *** [nccl_external-prefix/src/nccl_external-stamp/nccl_external-build] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nccl_external.dir/all' failed
make[1]: *** [CMakeFiles/nccl_external.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
root@w8pc:~/caffe2/build# find /usr -name libcudart.so.*
/usr/lib/x86_64-linux-gnu/libcudart.so.8.0
/usr/lib/x86_64-linux-gnu/libcudart.so.8.0.61
/usr/share/man/man7/libcudart.so.7.gz
root@w8pc:~/caffe2/build# ln -s /usr/lib/x86_64-linux-gnu/libcudart.so.8.0 /usr/lib64/
ln: target '/usr/lib64/' is not a directory: No such file or directory
root@w8pc:~/caffe2/build# mkdir /usr/lib64/
root@w8pc:~/caffe2/build# ln -s /usr/lib/x86_64-linux-gnu/libcudart.so.8.0 /usr/lib64/
root@w8pc:~/caffe2/build# make
[  0%] Performing build step for 'nccl_external'
Compiling src/core.cu                         > /root/caffe2/third_party/nccl/build/obj/core.o
Compiling src/all_gather.cu                   > /root/caffe2/third_party/nccl/build/obj/all_gather.o
...
```

**Comment by anatlin** [comment]
solved by installing NCCL by myself from NVIDIA and setting the 2 flags -DNCCL_INCLUDE_DIRS -DNCCL_LIBRARIES in the cmake command

**Comment by pjh5** [comment]
@toby5box can you try installing NCCL from Nvidia? You can find their installation guide here http://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html

**Comment by xucong-zhang** [comment]
This is indeed NCCL issue. 
Now we need to modify the line: https://github.com/pytorch/pytorch/blob/54db14e390f2d32e1212870b872c96fbca71c48a/third_party/nccl/Makefile#L16
