### ISSUE TITLE
Build issue on ubuntu 16 about CUDNN

### ISSUE THREAD

**Issue by hma02** [facebookarchive/caffe2#549]
As requested from issue #389, open a new issue here.

I have issue when building caffe2 on ubuntu 16. See below. 
I'm using gcc 5.4 and cudnn6.0.12 on ubuntu 16 (last time I was using gcc 4.8 and cudnn 5.1.5 on a ubuntu 14 and had the same problem.)

It seems something related to cudnn. I wonder if anyone can help.

Here is the configuration summary.
```bash
-- Adding -fopenmp
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_35
-- Found libcuda: /opt/cuda-8.0/lib64/stubs/libcuda.so
-- Found libnvrtc: /opt/cuda-8.0/lib64/libnvrtc.so
-- Found cuDNN: v6.0.21  (include: /export/mlrg/hma02/cudnn/include, library: /export/mlrg/hma02/cudnn/lib64)
-- Found NCCL    (include: /export/mlrg/hma02/.local/include, library: /export/mlrg/hma02/.local/lib/libnccl.so)
-- NCCL: /export/mlrg/hma02/.local/lib/libnccl.so
-- CUDA detected: 8.0
-- Found libcuda: /opt/cuda-8.0/lib64/stubs/libcuda.so
-- Found libnvrtc: /opt/cuda-8.0/lib64/libnvrtc.so
-- Does not need to define long separately.
-- This compiler has builtin_cpu_supports feature.
-- GCC 5.4.0: Adding gcc and gcc_s libs to link line
-- Including OPENCV binaries
-- Include NCCL operators
-- Including image processing operators
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- MPI operators skipped due to no MPI support
-- Automatically generating missing __init__.py files.
-- ******** Summary ********
-- General:
--   Git version           : v0.7.0-201-gb19def6
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /usr/bin/protoc
--   CXX flags             :  -fopenmp -std=c++11 -fPIC -Wno-narrowing
--   Build type            : Release
--   Compile definitions   : CAFFE2_USE_EIGEN_FOR_BLAS;CAFFE2_USE_GOOGLE_GLOG;CAFFE2_USE_GFLAGS;EIGEN_MPL2_ONLY
--
--   BUILD_SHARED_LIBS     : ON
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /export/mlrg/hma02/anaconda2/lib/libpython2.7.so
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--   USE_CNMEM             : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_GLOG              : ON
--   USE_GFLAGS            : ON
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_OPENCV            : ON
--     OpenCV version      : 3.1.0
--   USE_FFMPEG            :
--   USE_ZMQ               : OFF
--   USE_ROCKSDB           : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : ON
--   USE_NNPACK            : OFF
--   USE_OPENMP            : ON
--   USE_REDIS             : OFF
--   USE_GLOO              : ON
-- Configuring done
```
The error shows up at the following stage:

```
[ 76%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/conv_op_shared_gpu.cc.o
[ 76%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/tile_op_gpu.cc.o
[ 76%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/queue/queue_ops_gpu.cc.o
[ 76%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/sgd/learning_rate_op_gpu.cc.o
[ 77%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/sgd/iter_op_gpu.cc.o
[ 77%] Linking CXX shared library libCaffe2_GPU.so
[ 77%] Built target Caffe2_GPU
Scanning dependencies of target print_core_object_sizes
[ 77%] Building CXX object caffe2/CMakeFiles/print_core_object_sizes.dir/binaries/print_core_object_sizes.cc.o
[ 77%] Linking CXX executable binaries/print_core_object_sizes
[ 77%] Built target print_core_object_sizes
Scanning dependencies of target inspect_gpus
[ 78%] Building CXX object caffe2/CMakeFiles/inspect_gpus.dir/binaries/inspect_gpus.cc.o
[ 78%] Linking CXX executable binaries/inspect_gpus
libCaffe2_GPU.so: undefined reference to `cudnnSetLRNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnSetFilter4dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNLinLayerMatrixParams'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionForwardAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnCreateConvolutionDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyConvolutionDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetTensorNdDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionForwardAlgorithmEx'
libCaffe2_GPU.so: undefined reference to `cudnnSetFilterNdDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSoftmaxBackward'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionForward'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardDataAlgorithmEx'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNLinLayerBiasParams'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionForwardAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnLRNCrossChannelBackward'
libCaffe2_GPU.so: undefined reference to `cudnnPoolingBackward'
libCaffe2_GPU.so: undefined reference to `cudnnDropoutGetReserveSpaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnCreateTensorDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyDropoutDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnRNNForwardInference'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionBackwardData'
libCaffe2_GPU.so: undefined reference to `cudnnCreateDropoutDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardDataAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnCreatePoolingDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyFilterDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnBatchNormalizationForwardInference'
libCaffe2_GPU.so: undefined reference to `cudnnActivationBackward'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyTensorDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNParamsSize'
libCaffe2_GPU.so: undefined reference to `cudnnCreateLRNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyRNNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionForwardWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnDropoutBackward'
libCaffe2_GPU.so: undefined reference to `cudnnAddTensor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyPoolingDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetFilterNdDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSoftmaxForward'
libCaffe2_GPU.so: undefined reference to `cudnnActivationForward'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnGetVersion'
libCaffe2_GPU.so: undefined reference to `cudnnPoolingForward'
libCaffe2_GPU.so: undefined reference to `cudnnDeriveBNTensorDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnRNNBackwardWeights'
libCaffe2_GPU.so: undefined reference to `cudnnSetTensor4dDescriptorEx'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNTrainingReserveSize'
libCaffe2_GPU.so: undefined reference to `cudnnCreateRNNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDropoutGetStatesSize'
libCaffe2_GPU.so: undefined reference to `cudnnSetPooling2dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionBackwardBias'
libCaffe2_GPU.so: undefined reference to `cudnnBatchNormalizationBackward'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardFilterAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnCreateFilterDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetActivationDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnTransformTensor'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionBackwardFilter'
libCaffe2_GPU.so: undefined reference to `cudnnSetStream'
libCaffe2_GPU.so: undefined reference to `cudnnLRNCrossChannelForward'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyLRNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardFilterAlgorithmEx'
libCaffe2_GPU.so: undefined reference to `cudnnRNNBackwardData'
libCaffe2_GPU.so: undefined reference to `cudnnCreateActivationDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetTensor4dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroy'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyActivationDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetRNNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetConvolution2dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnBatchNormalizationForwardTraining'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnDropoutForward'
libCaffe2_GPU.so: undefined reference to `cudnnRNNForwardTraining'
libCaffe2_GPU.so: undefined reference to `cudnnSetDropoutDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnCreate'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/inspect_gpus.dir/build.make:130: recipe for target 'caffe2/binaries/inspect_gpus' failed
make[2]: *** [caffe2/binaries/inspect_gpus] Error 1
CMakeFiles/Makefile2:1488: recipe for target 'caffe2/CMakeFiles/inspect_gpus.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/inspect_gpus.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Also, as I'm not familiar with cmake, I wonder if there is a way to test building only the part that generates those errors instead of building from beginning each time? Thanks very much!

**Comment by hma02** [comment]
The problem is solved by building with the following command instead of simply `mkdir build && cd build && cmake .. && make`

```bash
mkdir build
cd build
cmake -DCUDNN_INCLUDE_DIR=path/to/cudnn/include -DCUDNN_LIBRARY=path/to/cudnn/lib64/libcudnn.so ..
make
```

The problem was that, CUDNN_LIBRARY somehow needed to be `path/to/cudnn/lib64/libcudnn.so` instead of `path/to/cudnn/lib64` . So we need to explicitly specify it with this cmake flag:
`-DCUDNN_LIBRARY=path/to/cudnn/lib64/libcudnn.so`

After this is done, you would see during configure:

```bash
-- Found cuDNN: v6.0.21  (include: /export/mlrg/hma02/cudnn/include, library: /export/mlrg/hma02/cudnn/lib64/libcudnn.so)
```
instead of:
```bash
-- Found cuDNN: v6.0.21  (include: /export/mlrg/hma02/cudnn/include, library: /export/mlrg/hma02/cudnn/lib64)
```
Another way to solve this problem is to put downloaded cudnn files into /usr/local/cuda/
```bash
tar -xvzf cudnn.tar.gz
cd cuda
mv lib64/* /usr/local/cuda/lib64/
mv include/* /usr/local/cuda/include/
```
After this is done, `mkdir build && cd build && cmake .. && make` will work as well.

This problem also shows up in building a previous version of [caffe](https://github.com/BVLC/caffe), though it doesn't show up with [caffe-nv](https://github.com/NVIDIA/caffe).

**Comment by lukeyeager** [comment]
If you're so inclined, you could use deb packages for installation to standard paths.

Instructions to access the repos: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md

**Comment by hma02** [comment]
@lukeyeager 

Thanks. Installing cudnn using deb packages will work as well. As I tried on a power8 machine which didn't show this problem during compilation because its cudnn was installed this way.

**Comment by houseroad** [comment]
Copy cudnn's so files to the cuda lib64 directory may also solve the problem.

**Comment by mrmartin** [comment]
It seems that caffe2 is looking for libcudnn.so, not libcudnn.so.*. Making a symlink from libcudnn.so.6.0.21 to libcudnn.so worked for me.

Use this with the cudnn version you actually have:
``ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21 /usr/lib/x86_64-linux-gnu/libcudnn.so``

**Comment by pietern** [comment]
This is typically managed by the distribution if you install a native package. For example, if you install the CuDNN deb then it will automatically create the libcudnn.so symlink (via update-alternatives).

Closing the issue.

**Comment by gjm441** [comment]
@hma02  I solved the problem as you did.Edit the makefile and then it works Well!

**Comment by FSet89** [comment]
where are the files that have to be copied into /usr/local/cuda?
