### ISSUE TITLE
Official Docker Image:Failure 

### ISSUE THREAD

**Issue by NinjaAtWork** [facebookarchive/caffe2#876]
Hi
following the [Install](https://caffe2.ai/docs/getting-started.html)  on win 8.1 platform with Docker image:
1-docker pull caffe2ai/caffe2:c2.tutorial.0.7.1         : OK
2-docker run -it caffe2ai/caffe2:c2.tutorial.0.7.1    : OK
3-python -m caffe2.python.operator_test.relu_op_test     :

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcuda.so.1: cannot open shared object file: No such file or directory
Segmentation fault

what can i do?im going to use CPU mode only,i have to set it manually?
-thanks

**Comment by pkrush** [comment]
Same here, except it was caffe2_pybind_state_gpu.so with last build on 6/26:
aa342f990f066cdc34192b8b7bb45426748dd113

I fixed it by adding /home/ubuntu/caffe2/build to $LD_LIBRARY_PATH

In #424:
"it you add the folder with caffe2_pybind_state_gpu.so to your LD_LIBRARY_PATH then you should be ok"

**Comment by yeshwanthv5** [comment]
I am having the same problem. Please tell me how if you have resolved it

**Comment by tampler** [comment]
Got the same issue for Ubuntu 14.04 Kernel 3.16.0-30.
Running 
docker run -it caffe2ai/caffe2:c2.tutorial.0.7.1 simply opens the docker shell.

Running root@1b77ea48a4c0:/# python caffe2/caffe2/python/examples/char_rnn.py 
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcuda.so.1: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)

**Comment by aaronmarkham** [comment]
@tampler I updated the docs page so that it references nvidia-docker which is what you'll want to use to get rid of the "libcuda.so.1: cannot open shared object file" error. Also, you'll want to use the [latest docker image](https://hub.docker.com/r/caffe2ai/caffe2/) v0.8 instead of the old 0.7.1 one.

**Comment by tampler** [comment]
Can't build v0.8.0 from Git Master. Get the following error:
home/bku/work/frameworks/caffe2/caffe2/operators/recurrent_network_op.h:766:50: error: cannot call member function ‘const T& caffe2::OperatorBase::Input(int) [with T = caffe2::Tensor<caffe2::CPUContext>]’ without object
         OperatorBase::Input<Tensor<CPUContext>>(0).template data<int32_t>()[0];

I need to Cross Compile this for ARM v7 32bit with a custom toolchain, based on Linaro GCC 7.1.1
Will try the latest docker soon

**Comment by aaronmarkham** [comment]
That seems like the #805 issue. Please open up a new issue related to docker if you have a problem with the latest. I'll be making some changes related to the suggestions in #949.

**Comment by hedes1992** [comment]
@NinjaAtWork I replace docker with nvidia-docker， it worked
![image](https://user-images.githubusercontent.com/14728901/38655361-b922e796-3e46-11e8-8a98-61f8b364225f.png)
